const artwork = (slug) => `/assets/games/generated/${slug}.jpg`;

export const GAMES_DATA = [
  { id: 1, title: "Just Cause 3", image: artwork("just-cause-3-action-art"), category: "Action", mode: "Single player" },
  { id: 2, title: "God of War", image: artwork("god-of-war-mythic-realm-art"), category: "Action RPG", mode: "Single player" },
  { id: 3, title: "Assassin's Creed", image: artwork("assassins-creed-shadow-city-art"), category: "Adventure", mode: "Single player" },
  { id: 4, title: "Red Dead Redemption 2", image: artwork("red-dead-redemption-2-western-art"), category: "Open world", mode: "Story" },
  { id: 5, title: "Counter-Strike 2", image: artwork("counter-strike-tactical-art"), category: "Tactical", mode: "Multiplayer" },
  { id: 6, title: "Grand Theft Auto V", image: artwork("gta-v-urban-heist-art"), category: "Open world", mode: "Online" },
  { id: 7, title: "Call of Duty", image: artwork("call-of-duty-modern-war-art"), category: "Shooter", mode: "Multiplayer" },
  { id: 8, title: "Ghost of Tsushima", image: artwork("ghost-of-tsushima-samurai-island-art"), category: "Adventure", mode: "Single player" },
  { id: 9, title: "Marvel's Spider-Man", image: artwork("spider-man-city-swing-art"), category: "Action", mode: "Single player" },
  { id: 10, title: "Resident Evil", image: artwork("resident-evil-survival-horror-art"), category: "Horror", mode: "Single player" },
  { id: 11, title: "GTA: San Andreas", image: artwork("gta-san-andreas-street-art"), category: "Open world", mode: "Single player" },
  { id: 12, title: "Assassin's Creed IV: Black Flag", image: artwork("assassins-creed-black-flag-pirate-art"), category: "Adventure", mode: "Single player" },
  { id: 13, title: "Nova Strike", image: artwork("nova-strike-mech-city-art"), category: "Sci-fi", mode: "Single player" },
  { id: 14, title: "GTA: Vice City", image: artwork("gta-vice-city-neon-art"), category: "Open world", mode: "Single player" },
  { id: 15, title: "League of Legends", image: artwork("league-of-legends-fantasy-arena-art"), category: "MOBA", mode: "Multiplayer" },
  { id: 16, title: "Elden Ring", image: artwork("elden-ring-golden-eclipse-art"), category: "Action RPG", mode: "Single player" },
  { id: 17, title: "The Last of Us Part II", image: artwork("last-of-us-part-2-overgrown-city-art"), category: "Adventure", mode: "Story" },
  { id: 18, title: "Battlefield 4", image: artwork("battlefield-4-armored-valley-art"), category: "Shooter", mode: "Multiplayer" },
  { id: 19, title: "Days Gone", image: artwork("days-gone-biker-wilderness-art"), category: "Survival", mode: "Single player" },
  { id: 20, title: "Need for Speed", image: artwork("need-for-speed-night-race-art"), category: "Racing", mode: "Single player" },
  { id: 21, title: "Warcraft", image: artwork("warcraft-fantasy-kingdom-art"), category: "Strategy", mode: "Multiplayer" },
  { id: 22, title: "Mafia II", image: artwork("mafia-2-noir-city-art"), category: "Action", mode: "Story" },
  { id: 23, title: "Tekken 7", image: artwork("tekken-7-martial-arts-arena-art"), category: "Fighting", mode: "Multiplayer" },
  { id: 24, title: "A Way Out", image: artwork("a-way-out-prison-escape-art"), category: "Co-op", mode: "Two players" },
  { id: 25, title: "Football Champions", image: artwork("football-champions-stadium-art"), category: "Sports", mode: "Multiplayer" },
  { id: 26, title: "F1 24", image: artwork("f1-24-grand-prix-art"), category: "Racing", mode: "Multiplayer" },
  { id: 27, title: "Gears of War 4", image: artwork("gears-of-war-4-alien-planet-art"), category: "Shooter", mode: "Co-op" },
  { id: 28, title: "Cricket Fever ZK19", image: artwork("cricket-fever-stadium-art"), category: "Sports", mode: "Multiplayer" },
  { id: 29, title: "Prince of Persia: The Two Thrones", image: artwork("prince-of-persia-ancient-palace-art"), category: "Adventure", mode: "Single player" },
  { id: 30, title: "Downhill Domination", image: artwork("downhill-domination-mountain-bike-art"), category: "Racing", mode: "Multiplayer" },
  { id: 31, title: "Dante's Inferno", image: artwork("dantes-inferno-underworld-art"), category: "Action", mode: "Single player" },
  { id: 32, title: "GreedFall", image: artwork("greedfall-frontier-art"), category: "RPG", mode: "Single player" },
  { id: 33, title: "Far Cry 6", image: artwork("far-cry-6-tropical-island-art"), category: "Action", mode: "Co-op" },
  { id: 34, title: "The Incredible Hulk", image: artwork("hulk-city-strength-art"), category: "Action", mode: "Single player" },
  { id: 35, title: "Warframe", image: artwork("warframe-orbital-warrior-art"), category: "Action RPG", mode: "Online" },
  { id: 36, title: "Forza Horizon 5", image: artwork("forza-horizon-5-desert-race-art"), category: "Racing", mode: "Multiplayer" },
  { id: 37, title: "Sekiro: Shadows Die Twice", image: artwork("sekiro-shinobi-temple-art"), category: "Action", mode: "Single player" },
  { id: 38, title: "Driver: San Francisco", image: artwork("driver-san-francisco-car-chase-art"), category: "Racing", mode: "Single player" },
  { id: 39, title: "Horizon Forbidden West", image: artwork("horizon-forbidden-west-wilds-art"), category: "Action RPG", mode: "Single player" },
  { id: 40, title: "The Witcher 3: Wild Hunt", image: artwork("witcher-wild-hunt-monster-realm-art"), category: "RPG", mode: "Single player" },
  { id: 41, title: "Batman: Arkham Knight", image: artwork("batman-arkham-knight-gothic-city-art"), category: "Action", mode: "Single player" },
  { id: 42, title: "SmackDown!", image: artwork("smackdown-wrestling-arena-art"), category: "Sports", mode: "Multiplayer" },
  { id: 43, title: "X-Men", image: artwork("x-men-mutant-team-art"), category: "Action", mode: "Co-op" },
  { id: 44, title: "Kingdom Come: Deliverance", image: artwork("kingdom-come-deliverance-medieval-art"), category: "RPG", mode: "Single player" },
  { id: 45, title: "Ancestors Legacy", image: artwork("ancestors-legacy-viking-campaign-art"), category: "Strategy", mode: "Multiplayer" },
  { id: 46, title: "Hell is Us", image: artwork("hell-is-us-surreal-landscape-art"), category: "Adventure", mode: "Single player" },
  { id: 47, title: "Rise of the Ronin", image: artwork("rise-of-the-ronin-japan-art"), category: "Action RPG", mode: "Single player" },
  { id: 48, title: "Senua's Saga: Hellblade II", image: artwork("senuas-saga-norse-art"), category: "Adventure", mode: "Story" },
  { id: 49, title: "Resident Evil Village", image: artwork("resident-evil-village-horror-art"), category: "Horror", mode: "Single player" },
  { id: 50, title: "Detroit: Become Human", image: artwork("detroit-become-human-android-city-art"), category: "Narrative", mode: "Story" },
];

export const FEATURED_GAMES = [
  {
    ...GAMES_DATA[15],
    eyebrow: "Editor's spotlight",
    description: "Cross a vast realm shaped by mystery, discovery, and unforgettable encounters.",
    heroImage: "/assets/games/generated/hero-elden-ring-golden-realm.jpg",
  },
  {
    ...GAMES_DATA[35],
    eyebrow: "Made for the road",
    description: "Chase the horizon through a vibrant open world built around pure driving freedom.",
    heroImage: "/assets/games/generated/hero-forza-horizon-road.jpg",
  },
  {
    ...GAMES_DATA[7],
    eyebrow: "Featured adventure",
    description: "Follow the wind across a breathtaking island where every path tells a story.",
    heroImage: "/assets/games/generated/hero-ghost-tsushima-island.jpg",
  },
];

export const GAME_CATEGORIES = [
  "All games",
  ...Array.from(new Set(GAMES_DATA.map(({ category }) => category))).sort(),
];
