export const GAMES_DATA = [
    { id: 1, title: "JUST CAUSE 3", image: "/assets/games/game1.jpeg", category: "Action" },
    { id: 2, title: "The Art Of GOD OF WAR", image: "/assets/games/game2.jpeg", category: "Racing" },
    { id: 3, title: "Assasins Creed", image: "/assets/games/game3.jpeg", category: "Simulation" },
    { id: 4, title: "Red Dead Redemption II", image: "/assets/games/game4.jpeg", category: "Strategy" },
    { id: 5, title: "Counter Strike", image: "/assets/games/game5.jpeg", category: "Action" },
    { id: 6, title: "GTA V", image: "/assets/games/game6.jpeg", category: "Indie" },
    { id: 7, title: "Call Of Duty", image: "/assets/games/game7.jpeg", category: "RPG" },
    { id: 8, title: "GHOST OF TSUSHIMA", image: "/assets/games/game8.jpeg", category: "Adventure" },
    { id: 9, title: "SPIDER MAN", image: "/assets/games/game9.jpeg", category: "Racing" },
    { id: 10, title: "RESIDENT EVIL", image: "/assets/games/game10.jpeg", category: "RPG" },
    { id: 11, title: "Grand Theft Auto San Andreas", image: "/assets/games/game11.jpeg", category: "Action" },
    { id: 12, title: "Assasins Creed Black Flag", image: "/assets/games/game12.jpeg", category: "Strategy" },
    { id: 13, title: "Nova Strike", image: "/assets/games/game13.jpeg", category: "Adventure" },
    { id: 14, title: "GTA Vice City", image: "/assets/games/game14.jpeg", category: "Action" },
    { id: 15, title: "League of Legends", image: "/assets/games/game15.jpeg", category: "Platformer" },
    { id: 16, title: "Elden Ring", image: "/assets/games/game16.jpeg", category: "Horror" },
    { id: 17, title: "The Last Of Us Part II", image: "/assets/games/game17.jpeg", category: "Action" },
    { id: 18, title: "BattleField 4", image: "/assets/games/game18.jpeg", category: "Simulation" },
    { id: 19, title: "Days Gone", image: "/assets/games/game19.jpeg", category: "Arcade" },
    { id: 20, title: "Need For Speed", image: "/assets/games/game20.jpeg", category: "Survival" },
    { id: 21, title: "War Craft", image: "/assets/games/game21.jpeg", category: "Indie" },
    { id: 22, title: "Mafia 2", image: "/assets/games/game22.jpeg", category: "Stealth" },
    { id: 23, title: "TEKKEN 7", image: "/assets/games/game23.jpeg", category: "Music" },
    { id: 24, title: "A Way Out", image: "/assets/games/game24.jpeg", category: "RPG" },
    { id: 25, title: "Foot Ball", image: "/assets/games/game25.jpeg", category: "Action" },
    { id: 26, title: "F1 24", image: "/assets/games/game26.jpeg", category: "Sci-Fi" },
    { id: 27, title: "Gears Of War 4", image: "/assets/games/game27.jpeg", category: "Shooter" },
    { id: 28, title: "Cricket Fever ZK19", image: "/assets/games/game28.jpeg", category: "Action" },
    { id: 29, title: "Prince Of Persia The Two Thrones", image: "/assets/games/game29.jpeg", category: "Rogue-like" },
    { id: 30, title: "DownHill DOMINATION", image: "/assets/games/game30.jpeg", category: "Action" },
    { id: 31, title: "Dantes Inferno", image: "/assets/games/game31.jpeg", category: "Metroidvania" },
    { id: 32, title: "GREED Fall", image: "/assets/games/game32.jpeg", category: "Platformer" },
    { id: 33, title: "Far CRY 6", image: "/assets/games/game33.jpeg", category: "Casual" },
    { id: 34, title: "HULK", image: "/assets/games/game34.jpeg", category: "Sandbox" },
    { id: 35, title: "WAEFRAME", image: "/assets/games/game35.jpeg", category: "Creative" },
    { id: 36, title: "FORZA HORIZAON 5", image: "/assets/games/game36.jpeg", category: "Community" },
    { id: 37, title: "SEKIRO SHADOWS DIE TWICE", image: "/assets/games/game37.jpeg", category: "Battle Royale" },
    { id: 38, title: "DRIVER san Francisco", image: "/assets/games/game38.jpeg", category: "Shooter" },
    { id: 39, title: "Horizon Forbidden West", image: "/assets/games/game39.jpeg", category: "MOBA" },
    { id: 40, title: "WITCHER WILD HUNT", image: "/assets/games/game40.jpeg", category: "eSports" },
    { id: 41, title: "BATMAN Arkham Knight", image: "/assets/games/game41.jpeg", category: "Strategy" },
    { id: 42, title: "SmackDown", image: "/assets/games/game42.jpeg", category: "Tactical" },
    { id: 43, title: "X-man", image: "/assets/games/game43.jpeg", category: "Shooter" },
    { id: 44, title: "Kingdam Come Deliverance ", image: "/assets/games/game44.jpeg", category: "Stealth" },
    { id: 45, title: "Ancestors Legacy", image: "/assets/games/game45.jpeg", category: "RPG" },
    { id: 46, title: "Hell is US", image: "/assets/games/game46.jpeg", category: "Action" },
    { id: 47, title: "RISE OF THE RONIN", image: "/assets/games/game47.jpeg", category: "Adventure" },
    { id: 48, title: "SENUA's SAGA HELLBLADE II", image: "/assets/games/game48.jpeg", category: "Action" },
    { id: 49, title: "VILLAGE RESIDENT EVIL", image: "/assets/games/game49.jpeg", category: "Adventure" },
    { id: 50, title: "DETROIT BECOME HUMAN", image: "/assets/games/game50.jpeg", category: "Story" },
];
